######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 16 14:29:04 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += emotionrank.h emotiontest.h mainwindow.h
SOURCES += emotionrank.cpp emotiontest.cpp main.cpp mainwindow.cpp
